const low = require('lowdb');
const FileSync = require('lowdb/adapters/FileSync');
const { v4: uuidv4 } = require('uuid');
const dataCreator = require('./dataCreator');

const adapter = new FileSync('data/data.json');
const db = low(adapter);

// Sets up database with some entry/s if the database file does not exist yet
db.defaults({
	contracts: [
		{
			id: '814c099a-3fb4-497a-91b7-3a2dd1434bbc', // an example id generated by uuidv4
			state: 'DRAFT', // using a string to determine if DRAFT or ACTIVE instead of bool, incase we want additional states in the future
			header: {
				name: 'Luke',
				address: 'Melbourne'
			},
			lines: [
				{ text: 'Line 0', originalValue: 1000, currentValue: 1000 },
				{ text: 'Line 1', originalValue: 2000, currentValue: 2000 },
			]
		}
    ],
    claims: [
        {
            id: '0bb76779-ce50-48cf-a65a-d0dc3d84393a', // an example id generated by uuidv4
            contractId: '814c099a-3fb4-497a-91b7-3a2dd1434bbc',
            state: 'DRAFT',
            respondent: 'Luke',
            claimant: 'Jeff',
            lines: [
                { lineIndex: 0, claimAmount: 500 },
                { lineIndex: 1, claimAmount: 1000 }
            ]
        }
    ]
}).write();

const searchContracts = (data) => {
	// Matching for a provided 'name' field and an 'address' field within the header field (case insensitive)
    return db.get('contracts').filter(({header}) => {
		return (data.name ? header.name.toLowerCase().includes(data.name.toLowerCase()) : true) &&
		(data.address ? header.address.toLowerCase().includes(data.address.toLowerCase()) : true)
	}).value();
}

const getContract = (id) => {
    return db.get('contracts').find({id}).value();
}

const putContract = (id, data) => {
    const contract = getContract(id);

    // Throw an error if the id provided does not refer to an existing document
    if (!contract) {
        throw new Error('Cannot find contract');
    }

    // Setting the data id to the contract's id so it remains consistent
    data.id = contract.id;

    return db.get('contracts')
        .find({id})
        .assign(data)
        .write();
}

const postContract = (data) => {
	const contract = dataCreator.createContract(data);
    db.get('contracts')
        .push(contract)
        .write();

    return contract;
}

const deleteContract = (id) => {

    return db.get('contracts')
		.remove({id})
		.write();
}

const searchClaims = (data) => {
	// Matching for a provided 'respondent' field and a 'claimant' field within the claim (case insensitive)
    return db.get('claims').filter(({respondent, claimant}) => {
		return (data.respondent ? respondent.toLowerCase().includes(data.respondent.toLowerCase()) : true) &&
		(data.claimant ? claimant.toLowerCase().includes(data.claimant.toLowerCase()) : true)
	}).value();
}

module.exports = {
	searchContracts,
	getContract,
	putContract,
	postContract,
    deleteContract,
    searchClaims
};